name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.2
  firebase_database: ^10.4.0
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ambulance.mp3
    


